### ISSUE TITLE
Issue: Cannot add new names

### ISSUE THREAD

**Issue by fxgcxrx** [pronouns/main#34] opened 2020-10-01 20:42 UTC
I used to be able to add names to my profile, but now when I type them and click add, nothing happens.

**Comment by kandiir4vr** [comment] 2020-11-01 21:37
I've had the same problem. After I click add, the name disappears and nothing happens.

**Comment by falkirks** [comment] 2020-11-02 19:17
@fxgcxrx @kandiir4vr What browser/device are you using?

**Comment by kandiir4vr** [comment] 2020-11-02 19:18
I tried to do it on chrome on both my android phone and my chromebook and neither worked

**Comment by falkirks** [comment] 2020-11-02 19:21
@kandiir4vr What is your pronouny username? You can also email me it at hi@noa.dev if you'd rather not comment it here.

**Comment by fxgcxrx** [comment] 2020-11-02 19:23
I use a Mac with google chrome/firefox. I also use an iPhone. 

My pronouny username is fagcore.

**Comment by ODeorain** [comment] 2020-11-22 06:55
I am now experiencing this problem on Opera.  I was able to enter about 3 names successfully before suddenly they all disappeared.  I now cannot add any more and none are displaying on my account.

**Comment by falkirks** [comment] 2020-12-22 15:36
This is now fixed in 8121764edc70c26de134efbe5e53d676942e104b! This was actually being caused by people having duplicate names.

**Closed by falkirks** 2020-12-22 15:36 UTC
